[package]
name = "DataOrchester"
version = "0.1.0"
edition = "2021"

[dependencies]
# Logger
log = "0.4"
env_logger = "0.11.7"

# Json Parser
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

# Random number generator
rand = "0.8"

ssh2 = "0.9.5"

ansi_term = "0.12.1"
